### ISSUE TITLE
Support build-time variables?

### ISSUE THREAD

**Issue by ceball** [6si/shipwright#87]
docker-compose supports [build-time arguments](https://docs.docker.com/compose/compose-file/#/args) for a service, e.g.

```
services:
  servicename:
    build:
      args:
        arg: value
```

Can I do something similar with shipwright? (Sorry if I missed it in the docs!)
